CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY 'admin';

GRANT ALL PRIVILEGES ON *.* to 'admin'@'%' IDENTIFIED BY 'admin' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* to 'admin'@'localhost' IDENTIFIED BY 'admin' WITH GRANT OPTION;

FLUSH PRIVILEGES;
