# Volumes
volumes:
    db_data:

#Docker Networks
networks:
    bridge:

# Services
services:
    php:
        env_file: .env
        container_name: "${DOCKER_APP_NAME}_php"
        build:
            context: .
            dockerfile: PHP.Dockerfile
        restart: unless-stopped
        # PHP-FPM port 9000
        ports:
            - "9000:9000"
            - "5173:5173"
        volumes:
            - ./www/${DOCKER_APP_NAME}:/app
            - ./etc/php:/usr/local/etc/php/conf.d/
            - ./shared:/shared
        working_dir: /app
        depends_on:
            - mariadb
            - adminer
            - redis
        networks:
            - bridge

    nginx:
        env_file: .env
        container_name: "${DOCKER_APP_NAME}_nginx"
        image: nginx:latest
        restart: unless-stopped
        working_dir: "/etc/nginx/conf.d"
        ports:
            - "80:80"
        networks:
            - bridge
        volumes:
            - ./etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./www/${DOCKER_APP_NAME}:/app
        environment:
            - DOCKER_APP_NAME=${DOCKER_APP_NAME}

    mariadb:
        env_file: .env
        container_name: "${DOCKER_APP_NAME}_mariadb"
        image: mariadb:latest
        restart: unless-stopped
        working_dir: "/etc/mysql/conf.d"
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
            - ./etc/mysql/mysql.conf:/etc/mysql/conf.d/my.cnf:ro
            - ./etc/mysql/init:/docker-entrypoint-initdb.d
        networks:
            - bridge

    adminer:
        env_file: .env
        container_name: "${DOCKER_APP_NAME}_adminer"
        image: adminer:latest
        restart: unless-stopped
        networks:
            - bridge
        ports:
            - "8080:8080"
        environment:
            - UPLOAD=${ADMINER_UPLOAD}
            - MEMORY=${ADMINER_MEMORY}

    redis:
        env_file: .env
        container_name: "${DOCKER_APP_NAME}_redis"
        image: "redis:alpine"
        restart: unless-stopped
        networks:
            - bridge
        ports:
            - "6379:6379"
        # command: >
        #  --requirepass ${REDIS_PASSWORD}
